version=1.2.2
group=se.itssimple.zombieshateslight
license=All rights reserved
java_version=25
source_url=https://github.com/itssimple/zombieshateslight
issue_tracker_url=https://github.com/itssimple/.mod-issue-tracker
credits=
cf.modules=forge;fabric
cf.moduleoutput.forge=C:/CurseForge/Instances/Forge ModTest/mods/;C:/CurseForge/Instances/NeoForge Test/mods/
cf.moduleoutput.fabric=C:/CurseForge/Instances/Fabric Test/mods/;C:/CurseForge/Instances/Quilt Test/mods/
minecraft_version=26.1
minecraft_version_range=[26.1]
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
mod_name=Zombies Hates Light
mod_author=NoLifeKing85
mod_id=zombieshateslight
description=Zombies will try to destroy your light sources
obsidianweave_version=1.1.5
forge_version=62.0.2
forge_loader_version_range=[62,)
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
neoforge_version=26.1.0.1-beta
neoloader_version=[4,)
neo_form_version=26.1-1
